// Copyright 2025, Algoryx Simulation AB.

#pragma once

// AGX Dynamics for Unreal includes.
#include "Terrain/TerrainParticleTypes.h"
#include "Terrain/AGX_Terrain.h"

// Unreal Engine includes.
#include "Components/ActorComponent.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "NiagaraComponent.h"

#include "AGX_SoilParticleRendererComponent.generated.h"

UCLASS(
	ClassGroup = "AGX_Terrain_Particle_Rendering", Blueprintable,
	meta = (BlueprintSpawnableComponent, ShortToolTip = "TODO: WRITE TOOL TIP"))
class AGXUNREAL_API UAGX_SoilParticleRendererComponent : public UActorComponent
{
	GENERATED_BODY()

public:

	UAGX_SoilParticleRendererComponent();

	/** Whether soil particles should be rendered or not. */
	UPROPERTY(EditAnywhere, Category = "AGX Soil Particle Rendering")
	bool bEnableParticleRendering = true;

	/**
	 * The Niagara VFX System that will be used to visualize the particles
	 * generated by the AGX_Terrain. This component will provide values to 
	 * the Niagara system if the corresponding inputs are declared as user
	 * parameters within the system (see the default PS_SoilParticleSystem).
	 * 
	 * Available Input:
	 * 
	 * - Array Float 4:	Positions And Scales
	 * - Array Float 4:	Orientations
	 * - Array Float 4:	Velocities And Masses
	 * - Array Bool:	Exists
	 * - int32:			Target Particle Count
	 */
	UPROPERTY(EditAnywhere, Category = "AGX Soil Particle Rendering", 
		Meta = (EditCondition = "bEnableParticleRendering"))
	UNiagaraSystem* ParticleSystemAsset;

	UFUNCTION(BlueprintCallable, Category = "AGX Soil Particle Rendering")
	bool SetEnableParticleRendering(bool bEnabled);

	UFUNCTION(BlueprintCallable, Category = "AGX Soil Particle Rendering")
	bool GetEnableParticleRendering();

	UFUNCTION(BlueprintCallable, Category = "AGX Soil Particle Rendering")
	UNiagaraComponent* GetParticleSystemComponent();

protected:

	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

#if WITH_EDITOR
	virtual void PostEditChangeChainProperty(FPropertyChangedChainEvent& Event) override;
	virtual void PostInitProperties() override;
#endif

private:

#if WITH_EDITOR
	void InitPropertyDispatcher();
#endif

	AAGX_Terrain* ParentTerrainActor = nullptr;

	UNiagaraComponent* ParticleSystemComponent = nullptr;

	FDelegateHandle DelegateHandle;

	bool InitializeParentTerrainActor();
	bool InitializeNiagaraParticleSystemComponent();
	void AssignDefaultNiagaraAsset(auto*& AssetRefProperty, const TCHAR* AssetPath);

	UFUNCTION()
	void HandleParticleData(FParticleDataById data);
};
